# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('autor', models.CharField(max_length=120)),
                ('editorial', models.CharField(max_length=120)),
                ('ISBN', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9999)),
            ],
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
