# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20170224_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
