# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_libro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='slug',
            field=models.SlugField(max_length=40),
        ),
    ]
